In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/workspaces/group-project-team1/fourth_downs_2024_2025.csv")

/tmp/ipykernel_23825/1165137578.py:1: DtypeWarning: Columns (0: timeout_team, 1: lateral_receiver_player_id, 2: lateral_receiver_player_name, 3: lateral_rusher_player_id, 4: lateral_rusher_player_name, 5: qb_hit_2_player_id, 6: qb_hit_2_player_name, 7: solo_tackle_2_team, 8: solo_tackle_2_player_id, 9: solo_tackle_2_player_name, 10: tackle_with_assist_1_player_id, 11: tackle_with_assist_1_player_name, 12: tackle_with_assist_1_team, 13: pass_defense_2_player_id, 14: pass_defense_2_player_name, 15: fumbled_2_player_id, 16: fumbled_2_player_name, 17: fumbled_2_team, 18: half_sack_1_player_id, 19: half_sack_1_player_name, 20: half_sack_2_player_id, 21: half_sack_2_player_name, 22: safety_player_name, 23: safety_player_id) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/workspaces/group-project-team1/fourth_downs_2024_2025.csv")

In [3]:
# Create list of unique start events
start_events = []
for e in data['drive_start_transition'].unique():
    start_events.append(e)

In [4]:
start_events

['FUMBLE',
 'KICKOFF',
 'PUNT',
 'DOWNS',
 'INTERCEPTION',
 'MUFFED_PUNT',
 'MISSED_FG',
 'MUFFED_KICKOFF',
 'BLOCKED_PUNT',
 'BLOCKED_FG,_DOWNS',
 'BLOCKED_PUNT,_DOWNS',
 'BLOCKED_FG',
 'ONSIDE_KICK']

In [5]:
# Find drives that started from kickoffs
# Onside kicks, kickoff, muffed_kickoff
# not fastest way but wanted to practice syntax and list comprehension
kickoff_events = [item for item in start_events if item == "KICKOFF" or "MUFFED_KICKOFF" in item or "ONSIDE_KICK" in item]
kickoff_events

['KICKOFF', 'MUFFED_KICKOFF', 'ONSIDE_KICK']

In [ ]:
#kickoff_data = data[data['drive_start_transition'].isin(kickoff_events)]
#kickoff_data.head()

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
1,1120,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0,0.473750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2360,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0,0.077613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2921,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0,0.161688,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3124,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,1,0,2.453890,NaN,NaN,NaN,NaN,NaN,0.791056,20.894444
7,3521,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0,-0.325116,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Look at what the values look like
#kickoff_data['drive_start_yard_line'][0:10]

1     BUF 30
2     ARI 30
5     ARI 30
6     BUF 30
7     BUF 30
10    ARI 40
11    BAL 30
14    BAL 30
16    BAL 30
17    BAL 30
Name: drive_start_yard_line, dtype: str

Create function to create new column
New column will split the current value at the ' ' (space), then check if the letters match 'posteam' value for the row. If they do, then the yardline will be 100-(number value). If they don't, then the value will be (number value)

In [ ]:
test = data[0:99]

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,823,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0,0.135574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1120,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0,0.473750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2360,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0,0.077613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2468,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0,0.210434,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2632,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0,1.343717,NaN,NaN,NaN,NaN,NaN,0.161714,-16.171412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,179,2024_01_HOU_IND,2024090804,IND,HOU,REG,1,IND,home,HOU,...,0,1,-3.753788,0.267124,3.909454,2.0,1.000000,1.000000,0.191990,80.801012
95,300,2024_01_HOU_IND,2024090804,IND,HOU,REG,1,HOU,away,IND,...,0,1,2.469806,0.552948,6.949968,5.0,0.985378,0.985378,0.201079,79.892129
96,395,2024_01_HOU_IND,2024090804,IND,HOU,REG,1,HOU,away,IND,...,0,1,1.343524,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,693,2024_01_HOU_IND,2024090804,IND,HOU,REG,1,HOU,away,IND,...,0,1,1.344061,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,805,2024_01_HOU_IND,2024090804,IND,HOU,REG,1,IND,home,HOU,...,0,1,1.282785,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# The 50 isn't owned by either team, so we need to have a condition for when drive_start_yard_line is 50.
for row in test.itertuples():
    print(f"Row drive_start_yard_line: {row.drive_start_yard_line}")
    row_off_team = row.posteam
    print(f"Row offense team: {row_off_team}")
    print(f"Row Defense team: {row.defteam}")
    try:

        if row.drive_start_yard_line == "50":
            print("Clean Yard Line: 50")
            continue

        row_yard_line_number = row.drive_start_yard_line.split(" ")[1]
        row_yard_line_team = row.drive_start_yard_line.split(" ")[0]
        if row_yard_line_team == row_off_team:
            print("Clean Yard Line: ", 100 - int(row_yard_line_number))
        else:
            print("Clean Yard Line: ", int(row_yard_line_number))
    except:
        print(f"ERROR. Row drive_start_yard_line: {row.drive_start_yard_line}",
              f"Row offense team: {row_off_team}",
              f"Row Defense team: {row.defteam}")

    print("------")

Row drive_start_yard_line: ARI 29
Row offense team: ARI
Row Defense team: BUF
Clean Yard Line:  71
------
Row drive_start_yard_line: BUF 30
Row offense team: BUF
Row Defense team: ARI
Clean Yard Line:  70
------
Row drive_start_yard_line: ARI 30
Row offense team: ARI
Row Defense team: BUF
Clean Yard Line:  70
------
Row drive_start_yard_line: BUF 31
Row offense team: BUF
Row Defense team: ARI
Clean Yard Line:  69
------
Row drive_start_yard_line: ARI 21
Row offense team: BUF
Row Defense team: ARI
Clean Yard Line:  21
------
Row drive_start_yard_line: ARI 30
Row offense team: ARI
Row Defense team: BUF
Clean Yard Line:  70
------
Row drive_start_yard_line: BUF 30
Row offense team: BUF
Row Defense team: ARI
Clean Yard Line:  70
------
Row drive_start_yard_line: BUF 30
Row offense team: BUF
Row Defense team: ARI
Clean Yard Line:  70
------
Row drive_start_yard_line: ARI 19
Row offense team: ARI
Row Defense team: BUF
Clean Yard Line:  81
------
Row drive_start_yard_line: ARI 42
Row offense team: BUF
Row Defense team: ARI
Clean Yard Line:  42
------
Row drive_start_yard_line: ARI 40
Row offense team: ARI
Row Defense team: BUF
Clean Yard Line:  60
------
Row drive_start_yard_line: BAL 30
Row offense team: BAL
Row Defense team: KC
Clean Yard Line:  70
------
Row drive_start_yard_line: KC 10
Row offense team: KC
Row Defense team: BAL
Clean Yard Line:  90
------
Row drive_start_yard_line: BAL 14
Row offense team: KC
Row Defense team: BAL
Clean Yard Line:  14
------
Row drive_start_yard_line: BAL 30
Row offense team: BAL
Row Defense team: KC
Clean Yard Line:  70
------
Row drive_start_yard_line: KC 49
Row offense team: KC
Row Defense team: BAL
Clean Yard Line:  51
------
Row drive_start_yard_line: BAL 30
Row offense team: BAL
Row Defense team: KC
Clean Yard Line:  70
------
Row drive_start_yard_line: BAL 30
Row offense team: BAL
Row Defense team: KC
Clean Yard Line:  70
------
Row drive_start_yard_line: KC 10
Row offense team: KC
Row Defense team: BAL
Clean Yard Line:  90
------
Row drive_start_yard_line: BAL 30
Row offense team: BAL
Row Defense team: KC
Clean Yard Line:  70
------
Row drive_start_yard_line: BAL 30
Row offense team: BAL
Row Defense team: KC
Clean Yard Line:  70
------
Row drive_start_yard_line: KC 30
Row offense team: KC
Row Defense team: BAL
Clean Yard Line:  70
------
Row drive_start_yard_line: CAR 40
Row offense team: NO
Row Defense team: CAR
Clean Yard Line:  40
------
Row drive_start_yard_line: CAR 26
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  74
------
Row drive_start_yard_line: CAR 25
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  75
------
Row drive_start_yard_line: NO 26
Row offense team: NO
Row Defense team: CAR
Clean Yard Line:  74
------
Row drive_start_yard_line: CAR 43
Row offense team: NO
Row Defense team: CAR
Clean Yard Line:  43
------
Row drive_start_yard_line: CAR 15
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  85
------
Row drive_start_yard_line: CAR 25
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  75
------
Row drive_start_yard_line: NO 36
Row offense team: NO
Row Defense team: CAR
Clean Yard Line:  64
------
Row drive_start_yard_line: CAR 32
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  68
------
Row drive_start_yard_line: CAR 30
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  70
------
Row drive_start_yard_line: NO 19
Row offense team: NO
Row Defense team: CAR
Clean Yard Line:  81
------
Row drive_start_yard_line: 50
Row offense team: CAR
Row Defense team: NO
Clean Yard Line: 50
Row drive_start_yard_line: NO 45
Row offense team: NO
Row Defense team: CAR
Clean Yard Line:  55
------
Row drive_start_yard_line: CAR 13
Row offense team: CAR
Row Defense team: NO
Clean Yard Line:  87
------
Row drive_start_yard_line: DAL 33
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  67
------
Row drive_start_yard_line: DAL 46
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  46
------
Row drive_start_yard_line: DAL 46
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  46
------
Row drive_start_yard_line: CLE 25
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  75
------
Row drive_start_yard_line: DAL 10
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  90
------
Row drive_start_yard_line: CLE 20
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  80
------
Row drive_start_yard_line: DAL 29
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  71
------
Row drive_start_yard_line: CLE 23
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  77
------
Row drive_start_yard_line: CLE 20
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  80
------
Row drive_start_yard_line: DAL 44
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  56
------
Row drive_start_yard_line: CLE 23
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  23
------
Row drive_start_yard_line: CLE 27
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  73
------
Row drive_start_yard_line: CLE 25
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  75
------
Row drive_start_yard_line: DAL 30
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  70
------
Row drive_start_yard_line: CLE 14
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  86
------
Row drive_start_yard_line: DAL 13
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  87
------
Row drive_start_yard_line: CLE 45
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  55
------
Row drive_start_yard_line: CLE 46
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  46
------
Row drive_start_yard_line: CLE 32
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  68
------
Row drive_start_yard_line: CLE 38
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  38
------
Row drive_start_yard_line: DAL 23
Row offense team: DAL
Row Defense team: CLE
Clean Yard Line:  77
------
Row drive_start_yard_line: CLE 36
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  64
------
Row drive_start_yard_line: CLE 36
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  64
------
Row drive_start_yard_line: CLE 36
Row offense team: CLE
Row Defense team: DAL
Clean Yard Line:  64
------
Row drive_start_yard_line: SEA 20
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  20
------
Row drive_start_yard_line: SEA 20
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  20
------
Row drive_start_yard_line: SEA 27
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  73
------
Row drive_start_yard_line: DEN 35
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  65
------
Row drive_start_yard_line: SEA 21
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  79
------
Row drive_start_yard_line: DEN 33
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  67
------
Row drive_start_yard_line: SEA 22
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  78
------
Row drive_start_yard_line: DEN 32
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  68
------
Row drive_start_yard_line: SEA 9
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  9
------
Row drive_start_yard_line: DEN 30
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  70
------
Row drive_start_yard_line: DEN 36
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  64
------
Row drive_start_yard_line: SEA 10
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  90
------
Row drive_start_yard_line: DEN 27
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  73
------
Row drive_start_yard_line: DEN 47
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  47
------
Row drive_start_yard_line: DEN 30
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  70
------
Row drive_start_yard_line: DEN 30
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  70
------
Row drive_start_yard_line: SEA 12
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  88
------
Row drive_start_yard_line: DEN 23
Row offense team: DEN
Row Defense team: SEA
Clean Yard Line:  77
------
Row drive_start_yard_line: SEA 38
Row offense team: SEA
Row Defense team: DEN
Clean Yard Line:  62
------
Row drive_start_yard_line: GB 35
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  65
------
Row drive_start_yard_line: GB 35
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  65
------
Row drive_start_yard_line: PHI 19
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  19
------
Row drive_start_yard_line: PHI 13
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  13
------
Row drive_start_yard_line: PHI 13
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  13
------
Row drive_start_yard_line: PHI 30
Row offense team: PHI
Row Defense team: GB
Clean Yard Line:  70
------
Row drive_start_yard_line: PHI 23
Row offense team: PHI
Row Defense team: GB
Clean Yard Line:  77
------
Row drive_start_yard_line: PHI 23
Row offense team: PHI
Row Defense team: GB
Clean Yard Line:  77
------
Row drive_start_yard_line: PHI 30
Row offense team: PHI
Row Defense team: GB
Clean Yard Line:  70
------
Row drive_start_yard_line: GB 20
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  80
------
Row drive_start_yard_line: GB 20
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  80
------
Row drive_start_yard_line: PHI 32
Row offense team: PHI
Row Defense team: GB
Clean Yard Line:  68
------
Row drive_start_yard_line: GB 30
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  70
------
Row drive_start_yard_line: GB 13
Row offense team: GB
Row Defense team: PHI
Clean Yard Line:  87
------
Row drive_start_yard_line: PHI 30
Row offense team: PHI
Row Defense team: GB
Clean Yard Line:  70
------
Row drive_start_yard_line: IND 27
Row offense team: IND
Row Defense team: HOU
Clean Yard Line:  73
------
Row drive_start_yard_line: HOU 47
Row offense team: HOU
Row Defense team: IND
Clean Yard Line:  53
------
Row drive_start_yard_line: HOU 47
Row offense team: HOU
Row Defense team: IND
Clean Yard Line:  53
------
Row drive_start_yard_line: HOU 30
Row offense team: HOU
Row Defense team: IND
Clean Yard Line:  70
------
Row drive_start_yard_line: IND 30
Row offense team: IND
Row Defense team: HOU
Clean Yard Line:  70
------

In [13]:
## Turn previous cell logic into a function to create a column for clean yard line
def clean_yard_line(row):
    row_off_team = row.posteam
    try:

        if row.drive_start_yard_line == "50":
            return 50

        row_yard_line_number = row.drive_start_yard_line.split(" ")[1]
        row_yard_line_team = row.drive_start_yard_line.split(" ")[0]
        if row_yard_line_team == row_off_team:
            return 100 - int(row_yard_line_number)
        else:
            return int(row_yard_line_number)
    except:
        return None

In [14]:
## Apply function to create new column
test['clean_yard_line'] = test.apply(clean_yard_line, axis=1)
test.head()

/tmp/ipykernel_23825/2644201213.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test['clean_yard_line'] = test.apply(clean_yard_line, axis=1)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,clean_yard_line
0,823,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0.135574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71
1,1120,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0.473750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
2,2360,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0.077613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
3,2468,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0.210434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69
4,2632,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,1.343717,NaN,NaN,NaN,NaN,NaN,0.161714,-16.171412,21

In [15]:
## Test on a larger subset of data
test_2 = data[0:1000]
test_2['clean_yard_line'] = test_2.apply(clean_yard_line, axis=1)
test_2.head()

/tmp/ipykernel_23825/621916673.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_2['clean_yard_line'] = test_2.apply(clean_yard_line, axis=1)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,clean_yard_line
0,823,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0.135574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71
1,1120,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0.473750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
2,2360,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0.077613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
3,2468,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0.210434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69
4,2632,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,1.343717,NaN,NaN,NaN,NaN,NaN,0.161714,-16.171412,21

In [16]:
## Function works!
data['clean_yard_line'] = data.apply(clean_yard_line, axis=1)
data.head()

/tmp/ipykernel_23825/4116402727.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['clean_yard_line'] = data.apply(clean_yard_line, axis=1)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,clean_yard_line
0,823,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0.135574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71
1,1120,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0.473750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
2,2360,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,ARI,away,BUF,...,0,0.077613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
3,2468,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,0.210434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69
4,2632,2024_01_ARI_BUF,2024090801,BUF,ARI,REG,1,BUF,home,ARI,...,0,1.343717,NaN,NaN,NaN,NaN,NaN,0.161714,-16.171412,21